### ISSUE TITLE
Scroll-bar on h1

### ISSUE THREAD

**Issue by germ13** [mhluska/pomodoro#1]
A scroll-bar is showing up on `<h1 class='title'> .... </h1>` on your production site (`http:\\timer.red`)

![pomodoro](https://cloud.githubusercontent.com/assets/146168/8473465/b1c49e4e-205e-11e5-8dc4-11e1f3121717.jpg)
.
.
.
I downloaded the repo today and built the site locally, it is not showing up.
![pomodoro2](https://cloud.githubusercontent.com/assets/146168/8473471/b94c00b2-205e-11e5-92a6-64633a457ebc.jpg)

I am running the latest version of chrome64 on windows.

**Comment by mhluska** [comment]
Is this still an issue for you? I updated the way minification happens during deploy so hopefully this went away.

**Comment by germ13** [comment]
Scrolling issue fixed, but image not rendering now.
Plus there was some misalignment introduced on 
I an including a screenshot of what chrome and firefox are rendering.
.

![pomodoro3](https://cloud.githubusercontent.com/assets/146168/8485002/895a18d4-20af-11e5-9778-23ea2637d05e.jpg)
buttons.

**Comment by mhluska** [comment]
Oops. Sorry about that. Alignment issues should be fixed now. If you're still having problems, please give me your browser version and I will debug.

The logo was removed intentionally since I found it to be a bit ugly. I'm looking for something better currently.
